server:
#  port: 8080
  servlet:
    context-path: /api
  reactive:
    session:
      timeout: 3600
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://101.43.61.87:3306/user_center
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bf389934.@
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
