server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
