server:
  port: 8090
  servlet:
    context-path: /api
  reactive:
    session:
      timeout: 3600
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
